train_model:
  _target_: src.reward_models.ClipTI
  src_img_dir: "dog"
  placeholder_token: "sks"
  class_name: "dog"
  t_weight: 0.5
val_models:
  - _target_: src.reward_models.DreamBench
    config:
      src_img_dir: "dog"
      placeholder_token: "sks"
      class_name: "dog"
      prompts_path: "dreambench-prompts"
      qwen_batch: 2
