train:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  num_workers: 4
  pin_memory: True
  shuffle: True
val:
  _target_: torch.utils.data.DataLoader
  batch_size: 1
  num_workers: 4
  pin_memory: True
  shuffle: True
