train:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 8
  pin_memory: True
  shuffle: True
test:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  num_workers: 16
  pin_memory: True
